### ISSUE TITLE
Cannot convert BigInt to Arb

### ISSUE THREAD

**Issue by lucifer1004** [kalmarek/Arblib.jl#134]
Currently, trying to do something like

```julia
a = Arb(big"3284738924733239284")
```

throws `InexactError`.

**Comment by lucifer1004** [comment]
I ran into this issue when trying to use `Arblib.jl` with `WignerSymbols.jl`, in which the Clebsch-Gordan coefficients are stored as `RationalRoot{BigInt}`.

**Comment by lucifer1004** [comment]
A possible workaround is to convert `BigInt` to `BigFloat` first, then convert the `BigFloat` to `Arb`.

**Comment by Joel-Dahne** [comment]
I have also encountered this at some point and went with the same solution of converting to `BigInt` first. 

To properly handle this you would have to make a constructor which first converts the `BigInt` (which is just a GMP integer in the background) into a Flint integer (`fmpz_t`) and then construct an `Arb` from that. This would require creating a struct for storing a `fmpz_t` as well. 

When I last encountered this I didn't feel like putting all that work into it, but in the long run I definitely think it is something we should support. Feel free to submit a pull request if you want to get it fixed soon! Otherwise I'll probably try to get it done at some point at least!

**Comment by Joel-Dahne** [comment]
Closed by #137
