### ISSUE TITLE
use LoadFlint

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/Arblib.jl#14]
since we require libflint, we may as well use the one provided by LoadFlint.jl:
https://github.com/oscar-system/LoadFlint.jl

**Comment by Joel-Dahne** [comment]
I think this would be an excellent idea! This would make it a lot easier to move from Nemo to Arblib for me, since I would be able to rewrite it in steps an not have it crash if I load both packages at the same time.

As a bonus this would make it possible to rely on Nemo for a Julia interface to `fmpz` and `fmpq`.

**Comment by kalmarek** [comment]
I think flint deserves its own `Flint.jl`, maybe even in similar spirit what we're doing here, but separate from our efforts; @saschatimme?

**Comment by saschatimme** [comment]
Let’s finish this first 😂

**Comment by kalmarek** [comment]
sorry everyone, I accidentally pushed to `master` this change 3f1ecc7

**Comment by saschatimme** [comment]
I don't mind
