### ISSUE TITLE
update arbcalls

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/Arblib.jl#145]
Today I found
https://arblib.org/acb.html#c.acb_add_error_arb
which is not covered by our arbcalls.

@Joel-Dahne I remember you kept your private version of arb docs ;) could you generate new calls?

**Comment by Joel-Dahne** [comment]
This method was added in Arb version 2.21.0 and unfortunately `Arb_jll` is still on version 2.20.1 so it wouldn't work even if we added it. I'm not sure how to ask for `Arb_jll` to be updated?

I bigger problem is that reparsing the documentation might not be as easy. I upstreamed all of my private updates to the documentation so there was a time when the official version could be parsed. However the documentation has been updated since then and parts of it has changed format. In version 2.20.0 all functions in the documentation were written as
```
.. function:: void arb_init(arb_t x)
```
and we could easily find them from the `.. function::` part. In version 2.21.1 this is not always the case, now they sometimes look like
```
.. function:: void arb_fma(arb_t res, const arb_t x, const arb_t y, const arb_t z, slong prec)
              void arb_fma_arf(arb_t res, const arb_t x, const arf_t y, const arb_t z, slong prec)
              void arb_fma_ui(arb_t res, const arb_t x, ulong y, const arb_t z, slong prec)
```
so our parsing logic has to be updated. There might be other changes as well which I have missed (there are also some new typos, but those can be fixed with some work).

**Comment by kalmarek** [comment]
we probably need to ask @fingolfin to update Arb_jll from Yggdrasil to the newest version.

For the docs parsing issue our best bet is to humbly ask @fredrik-johansson to revert the change/modify the docs. Otherwise we need to roll out our own rst parser (or use something existing?)

**Comment by fingolfin** [comment]
Anybody can submit updates for any JLL on Yggdrasil, you don't need me for that

**Comment by fredrik-johansson** [comment]
This is apparently how Sphinx wants groups of functions to be documented now, so I intend to change all the documentation over to the new format. I suggest somehow updating the parser. Surely some really simple ad hoc code will do the job?

**Comment by kalmarek** [comment]
@fingolfin Well, I've seen you making the last changes to Yggdrasils Arb on Oct 30 when Arb-2.21.1 already had been released. I assumed you had some reasons not to bump to the latest version ;) but if there are none, this one is ready https://github.com/JuliaPackaging/Yggdrasil/pull/4090 ;)

**Comment by Joel-Dahne** [comment]
> This is apparently how Sphinx wants groups of functions to be documented now, so I intend to change all the documentation over to the new format. I suggest somehow updating the parser. Surely some really simple ad hoc code will do the job?

@fredrik-johansson Thank you for the info! If that's the case then it should just be a matter of updating the parser, I don't think it should be too complicated. As before I'll upstream any fixes to the documentation I make. I'm hesitant to make other changes to the documentation just because we happen to need them, that we parses the documentation should be our problem and not Arbs, the format of the documentation should obviously not be treated as part of the API. 

I can try to make the updates in the coming week or so!
